### ISSUE TITLE
Make OTP QR with proper format for google authenticator

### ISSUE THREAD

**Issue by skironDotNet** [JanisEst/KeePassQRCodeView#9]
So the reason I wanted to use this plugin was to be able to import OTP to Google Auth on Android
Let say the OTP private key value is 123456 and KeePass Entry Title is AccountA
Your plugin will just generate simple QR with value:
key=123456 

This is not valid format I would expect something like https://qr.greenhex.net/#en/2fa does where the QR value is 
otpauth://totp/AccountA?secret=123456

This value is understood by google authenticator and can be just scanned and imported automatically

**Comment by skironDotNet** [comment]
Actually I didn't look at the code. It's C# so I can code it myself :)

**Comment by JanisEst** [comment]
The plugin simply prints the string value of a field as QR code. It's not intended to support any custom format.
I simply create a new custom string and reference other fields if I need it.
Example WLAN:
`WIFI:S:{S:SSID};T:WPA;P:{S:Password};;`
Now I can select this item for the QR code and I get a correct formatted code without any code changes.

**Comment by skironDotNet** [comment]
Yeah I have no idea how to debug the plugins, in fact I messed things to the level KeePass doesn't load any plugins. And I also don't understand how your plugin build in .NET 4.0 load into KeePass build in .NET 2.0 but I'm sure there is some magic using --plgx-create flag.

I'll try custom strings. Too bad you don't have it documentation. Also OTP is a standards, so you could do simple if filedName.ToLower() == "otp" then generate QR using OTP format, but your creation your decision.

Thanks for quick reply. You saved me lots of time

**Comment by skironDotNet** [comment]
I think the custom string is not what I was thinking about. I thought you use autotype configuration. I don't want to put custom filed with OTP format. there is a plugin for OTP that you enter a key and it does store it as "otp" item with value "key={acutallOtpKey}". Why would  enter a custom files with "otpauth://totp/AccountA?secret=123456" that defeats the purpose of having plugins, I can just go to https://qr.greenhex.net/#en/2fa and generate QR from value copied from otp field

**Comment by JanisEst** [comment]
In your string you should reference the "otp" field.

`otpauth://totp/{USERNAME}?secret={S:otp}`

Example:
Email is in default username field
OTP Seed is in custom field "TOTP Seed" (KeeTryTOTP plugin)

`otpauth://totp/{USERNAME}?secret={T-REPLACE-RX:/{S:TOTP Seed}/ //}`
The text replace is because the seed contains spaces after each block.
This results in
`otpauth://totp/test@example.org?secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
displayed as qr code
![qr](https://user-images.githubusercontent.com/35335635/54392012-d09d5c80-46a6-11e9-8f81-5b25deff1c12.jpg)
which can be read by Google Authenticator
![Screenshot_20190314-221407](https://user-images.githubusercontent.com/35335635/54392140-2245e700-46a7-11e9-9c5c-086a6f00b7ab.jpg)

Where do you have problems?

**Comment by skironDotNet** [comment]
Good luck with entering custom strings 50 times. With KeyOtp I just enter main key, with your plugin modified my way, I can generate QR out of it. Automation! But I'll not try to convince you except the fact that again if someone is not using KeyOtp your plugin act same way as is now, with my mod once, otp is present will return otpauth. There is no point to store otp and gen raw key QR just to what enter it manually or copy/paste from QR reader app back to Google Auth?

As for KeeTryTOTP vs KeyOtp the code can be modified to support both filed names. I coded only for KeyOtp because I use that one.

Also secret={S:otp} won't work because otp has value "key=xxxxx" and to gen otpauth you need just THE key "xxxxx" so in your case using secret={S:otp} will produce secret=key=xxxxx and that is invalid

**Comment by JanisEst** [comment]
`otpauth://totp/{T-CONV:/{TITLE}/Uri/}?secret={T-REPLACE-RX:/{S:otp}/key=//}`

**Comment by skironDotNet** [comment]
Damn, you are master of KeePass, I appreciate that, but since I want to put like 50 otps to KP I don't feel like doing 50x custom strings, in fact I don't want to think about it, so I rolled my version.
https://github.com/skironDotNet/KeePassQRCodeView/releases

P.S.
I'm glad you didn't merge the pull request it was buggy due to C# syntax of $"" is not handled well by plgx compilation when KP loads the plugin. 

And thanks for great work of KeePassQRCodeView

**Comment by lucvw1975** [comment]
Hi,

Can anyone help me configuring this plugin. I have been busy for a couple of hours, trying some plugins, but haven't found one that works (probably because I did something wrong). So what I want is that after inputting the master pwd for the db, the Google Authenticator app generates a value which I can use to sign in. I have been the victim of hackers, so I want to protect  my data and especially my passwords as much as I can...

Thanks ! :)
